title: Agile Engineering Fluency
description: A model for undertanding the specific proficiencies involved in creating a good 2+star agile team. Initial draft presented at Agile 2013.
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
